# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48fcc5a762ad914710670a29d388b7747edcd118769bcac5399f70b3aad0efe8dfcda76757671a9574164f3c8d1f47093822a506d07a0220d22493c596ca6f04

test:
  secret_key_base: 150357e723db39922586548a0a906054f4a3efa0c3eda9cd7ecd6829f38f835d1bbe4e7c293b368eb0037afc7045acafa67ad8f601e6fb228dc549aaf687f90f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
